create or replace TABLE IOWA_LIQUOR.EDW.DIM_CATEGORY (
	CATEGORY_SK NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	CATEGORY_ID NUMBER(38,0),
	CATEGORY_NAME VARCHAR(255),
	DI_CREATEDATE DATE,
	DI_JOBPID VARCHAR(30),
	primary key (CATEGORY_SK)
);

create or replace TABLE IOWA_LIQUOR.EDW.DIM_CITY (
	CITY_SK NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	CITY_NAME VARCHAR(255),
	DI_CREATEDATE DATE,
	DI_JOBPID VARCHAR(30),
	primary key (CITY_SK)
);

create or replace TABLE IOWA_LIQUOR.EDW.DIM_COUNTY (
	COUNTY_SK NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	COUNTY_NUMBER NUMBER(38,0),
	COUNTY_NAME VARCHAR(255),
	DI_CREATEDATE DATE,
	DI_JOBPID VARCHAR(30),
	primary key (COUNTY_SK)
);

create or replace TABLE IOWA_LIQUOR.EDW.DIM_DATE (
	DATE_SK NUMBER(38,0) NOT NULL,
	DATE DATE,
	DAY_NUM NUMBER(38,0) NOT NULL,
	MONTH_NUM NUMBER(38,0) NOT NULL,
	YEAR_NUM NUMBER(38,0) NOT NULL,
	IS_WEEKEND VARCHAR(1) NOT NULL,
	QTR_NUM NUMBER(38,0) NOT NULL,
	DAY_STR VARCHAR(20) NOT NULL,
	MONTH_STR VARCHAR(20) NOT NULL,
	DI_CREATEDATE DATE,
	DI_JOBPID VARCHAR(60),
	constraint PK_DATE_SK primary key (DATE_SK)
);

create or replace TABLE IOWA_LIQUOR.EDW.DIM_LOCATION (
	LOCATION_SK NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	ADDRESS VARCHAR(255),
	CITY_SK NUMBER(38,0),
	COUNTY_SK NUMBER(38,0),
	ZIP_CODE VARCHAR(10),
	LATITUDE VARCHAR(30),
	LONGITUDE VARCHAR(30),
	STATE VARCHAR(255),
	DI_CREATEDATE DATE,
	DI_JOBPID VARCHAR(30),
	primary key (LOCATION_SK),
	foreign key (CITY_SK) references IOWA_LIQUOR.EDW.DIM_CITY(CITY_SK),
	foreign key (COUNTY_SK) references IOWA_LIQUOR.EDW.DIM_COUNTY(COUNTY_SK)
);

create or replace TABLE IOWA_LIQUOR.EDW.DIM_PRODUCT (
	PRODUCT_SK NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	ITEM_NUMBER VARCHAR(30),
	ITEM_DESCRIPTION VARCHAR(255),
	BOTTLE_VOLUME_ML NUMBER(38,0),
	PACK NUMBER(38,0),
	INNER_PACK NUMBER(38,0),
	AGE NUMBER(38,0),
	PROOF NUMBER(38,0),
	LIST_DATE DATE,
	UPC NUMBER(38,0),
	SCC NUMBER(38,0),
	STATE_BOTTLE_COST NUMBER(10,2),
	STATE_CASE_COST NUMBER(10,2),
	STATE_BOTTLE_RETAIL NUMBER(10,2),
	DI_CREATEDATE DATE,
	DI_JOBPID VARCHAR(30),
	primary key (PRODUCT_SK)
);

create or replace TABLE IOWA_LIQUOR.EDW.DIM_STORE (
	STORE_SK NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	STORE_ID NUMBER(38,0),
	STORE_NAME VARCHAR(255),
	STORE_STATUS VARCHAR(1),
	DI_CREATEDATE DATE,
	DI_JOBPID VARCHAR(30),
	primary key (STORE_SK)
);

create or replace TABLE IOWA_LIQUOR.EDW.DIM_VENDOR (
	VENDOR_SK NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	VENDOR_ID VARCHAR(50),
	VENDOR_NAME VARCHAR(255),
	DI_CREATEDATE DATE,
	DI_JOBPID VARCHAR(30),
	primary key (VENDOR_SK)
);

create or replace TABLE IOWA_LIQUOR.EDW.FACT_CITY_POPULATION_BY_YEAR (
	CITY_POPULATION_SK NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	CITY_SK NUMBER(38,0),
	YEAR NUMBER(38,0),
	POPULATION NUMBER(38,0),
	DI_CREATEDATE DATE,
	DI_JOBPID VARCHAR(30),
	primary key (CITY_POPULATION_SK),
	foreign key (CITY_SK) references IOWA_LIQUOR.EDW.DIM_CITY(CITY_SK)
);

create or replace TABLE IOWA_LIQUOR.EDW.FACT_COUNTY_POPULATION_BY_YEAR (
	COUNTY_POPULATION_SK NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	COUNTY_SK NUMBER(38,0),
	YEAR NUMBER(38,0),
	POPULATION NUMBER(38,0),
	DI_CREATEDATE DATE,
	DI_JOBPID VARCHAR(30),
	primary key (COUNTY_POPULATION_SK),
	foreign key (COUNTY_SK) references IOWA_LIQUOR.EDW.DIM_COUNTY(COUNTY_SK)
);

create or replace TABLE IOWA_LIQUOR.EDW.FACT_SALES (
	SALES_SK NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	INVOICE_ITEM_NUMBER VARCHAR(30),
	DATE_SK NUMBER(38,0),
	STORE_SK NUMBER(38,0),
	LOCATION_SK NUMBER(38,0),
	PRODUCT_SK NUMBER(38,0),
	CATEGORY_SK NUMBER(38,0),
	VENDOR_SK NUMBER(38,0),
	PACK NUMBER(38,0),
	STATE_BOTTLE_COST NUMBER(10,2),
	STATE_BOTTLE_RETAIL NUMBER(10,2),
	BOTTLES_SOLD NUMBER(38,0),
	SALE_DOLLARS NUMBER(18,2),
	VOLUME_SOLD_LITERS NUMBER(18,2),
	VOLUME_SOLD_GALLONS NUMBER(18,2),
	DI_CREATEDATE DATE,
	DI_JOBPID VARCHAR(100),
	primary key (SALES_SK),
	foreign key (DATE_SK) references IOWA_LIQUOR.EDW.DIM_DATE(DATE_SK),
	foreign key (STORE_SK) references IOWA_LIQUOR.EDW.DIM_STORE(STORE_SK),
	foreign key (LOCATION_SK) references IOWA_LIQUOR.EDW.DIM_LOCATION(LOCATION_SK),
	foreign key (PRODUCT_SK) references IOWA_LIQUOR.EDW.DIM_PRODUCT(PRODUCT_SK),
	foreign key (VENDOR_SK) references IOWA_LIQUOR.EDW.DIM_VENDOR(VENDOR_SK),
	foreign key (CATEGORY_SK) references IOWA_LIQUOR.EDW.DIM_CATEGORY(CATEGORY_SK)
);